// Message Generator apps
const messageGenerator = {
    subject: ["L'attaquant",
              "Le défenseur",
              "Le gardien",
              "Le joueur de tennis",
              "Le coureur",
              "Le nageur",
              "Le boxeur",
              "L'arbitre",
              "L'entraîneur",
              "L'équipe",],
    verb: ["marque",
           "défend",
           "bloque",
           "sert",
           "court",
           "nage",
           "frappe",
           "siffle",
           "entraîne",
           "gagne",],
    noun: ["un but",
           "une passe",
           "une frappe",
           "un ace",
           "un sprint",
           "une longueur",
           "un coup",
           "une faute",
           "un exercice",
           "le match",],


}

